language: node_js
node_js:
  - node
  - lts/*
matrix:
  allow_failures:
    - node_js: node
before_install:
  - npm --global install npm
  - npm --global install greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
