on:
  push:
  workflow_call:

jobs:
  commitlint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v6
        with:
          node-version: latest
      - run: npm --global install npm@latest
      - run: npm --version
      - run: npm ci
      # Hiding tsconfig.json to workaround
      # https://github.com/conventional-changelog/commitlint/issues/3256
      - run: mv tsconfig.json tsconfig.json.nope
      - name: commitlint
        run: |
          npx commitlint \
            --from ${{ github.event.pull_request.head.sha }}~${{ github.event.pull_request.commits }} \
            --to ${{ github.event.pull_request.head.sha }} \
            --verbose
      - run: mv tsconfig.json.nope tsconfig.json

  # The test job ends up as multiple jobs and therefore as multiple checks.
  # Each check's name ends up with the node version appended.
  # If we were to use those checks as required checks, we would have to occasionally bump them.
  # This job allows us to have a single check that we don't have to bump.
  test-matrix:
    needs: test
    runs-on: ubuntu-latest
    if: ${{ !cancelled() }}
    steps:
      - run: if [ "${{ needs.test.result }}" != 'success' ]; then exit 1; fi
  test:
    needs: get-supported-node-versions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ${{ fromJson(needs.get-supported-node-versions.outputs.versions) }}
    name: Node.js v${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm --global install npm@latest
      - run: npm --version
      - run: npm install
      - run: npm test
      - uses: numtide/clean-git-action@v2
  get-supported-node-versions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - id: get
        run: |
          set -euxo pipefail
          active_versions=$(bash get-node-supported-versions.sh)
          echo "active=$active_versions" >> "$GITHUB_OUTPUT"
    outputs:
      versions: ${{ steps.get.outputs.active }}
